---
- name: ipaddress
  hosts: nodes # This value is taken from the inventory /etc/ansible/hosts
  gather_facts: yes
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]
